### ISSUE TITLE
相机直接打不开？

### ISSUE THREAD

**Issue by lc-alpha** [xionger0520/flowcamera#16]
java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.impl.PreviewConfig@5117937, androidx.camera.core.impl.VideoCaptureConfig@ac25bd1, androidx.camera.core.impl.ImageCaptureConfig@28e125b]

**Comment by xionger0520** [comment]
@lc-alpha 什么机型？？用的哪个版本？？？给权限了吗？？

**Comment by lc-alpha** [comment]
小米手机  权限开了的， 直接运行的demo就报错了

**Comment by xionger0520** [comment]
@lc-alpha 那你试试CustomCameraView版本

**Comment by lc-alpha** [comment]
我现在是直接运行你的demo，就报错了，No supported surface combination is found for camera device - Id : 0，说的不支持

**Comment by xionger0520** [comment]
@lc-alpha 听不懂我的意思么？demo是FlowCameraView让你换成CustomCameraView再试试。

**Comment by lc-alpha** [comment]
ok了，CustomCameraView这个版本是可以的
