### ISSUE TITLE
用的 kotlin就很难受，还是java比较好用啊

### ISSUE THREAD

**Issue by SunshineflowerLee** [xionger0520/flowcamera#27]

**Comment by xionger0520** [comment]
@SunshineflowerLee 就示例那点kt代码都看不懂？

**Comment by SunshineflowerLee** [comment]
@xionger0520 不是，看肯定看的懂，只是我要拿来改的，就比较麻烦，写起来不熟悉，然后camerax一用就报错（No supported surface combination is found for camera device - Id : 0 ）Android系统6.0的魅族m5，custom的和原著差不多，不过录制视频一开始画面必定卡住一会

**Comment by xionger0520** [comment]
@能看得懂不就行了  你改它干什么  你自己不会重写一个  兼容性问题 要么等更新 要么你用其他的框架

**Comment by xionger0520** [comment]
@SunshineflowerLee 能看得懂不就行了 你改它干什么 你自己不会重写一个 兼容性问题 要么等更新 要么你用其他的框架

**Comment by SunshineflowerLee** [comment]
@xionger0520 我自己写没问题，只不过是项目赶着用，想着就先找其它的，反正您这个也是没法用的，我也不会选，我要改只是因为项目需求不同，很正常，最后说一句，开发者应该为别人帮自己找到bug而高兴，我们来这是分享代码互相学习的，你如果以为我在嫌弃你的代码，那你格局可真小

**Comment by xionger0520** [comment]
@SunshineflowerLee 那赶紧滚
