### ISSUE TITLE
预览时和拍照后照片不一样，切换前后摄像头，拍照时屏幕都会黑一下

### ISSUE THREAD

**Issue by guofeiyua** [xionger0520/flowcamera#3]

**Comment by xionger0520** [comment]
预览和拍照的照片不是不一样  只是有些许差别  因为预览的时候是全屏但是拍摄的时候是有宽高比的
并且拍摄完成后的预览是居中裁剪的  所以范围会小一点  影响不大  黑一下的问题是CameraX的问题   等更新 @guofeiyua

**Comment by xionger0520** [comment]
@guofeiyua 升级到1.0.5 使用CustomCameraView试试

**Comment by guofeiyua** [comment]
这两个问题没了，但闪光灯和聚焦还有些问题，闪光灯和点击屏幕聚焦不起作用

**Comment by xionger0520** [comment]
@guofeiyua 闪光灯有啥问题么   现在是自动对焦不需要手动点击屏幕

**Comment by guofeiyua** [comment]
闪光灯在开启的状态下，点击拍照没有亮

**Comment by xionger0520** [comment]
你找个黑一点地方    太亮看不出来 有三个状态  图标是闪电带字母A的时候是自动     闪电是开启   剩下一个是关闭    切换到开启状态再试 @guofeiyua

**Comment by guofeiyua** [comment]
我试了，在开启的状态下，没有闪

**Comment by xionger0520** [comment]
@guofeiyua 测试了一下 发现确实没有开启闪光灯   原因是当前极速拍摄模式不支持闪光灯   考虑当前模式去除闪光灯

**Comment by xionger0520** [comment]
@guofeiyua 此问题已修复 用flow版本测一下
