### ISSUE TITLE
不能选择只拍照

### ISSUE THREAD

**Issue by f1mert** [xionger0520/flowcamera#5]

**Comment by xionger0520** [comment]
@f1mert 暂未提供单独设置拍照和录像的方法  之后版本考虑加入

**Comment by xionger0520** [comment]
@f1mert 已支持 单独拍照拍视频

**Comment by nxnyk** [comment]
> @f1mert 已支持 单独拍照拍视频

大佬考虑下 只把预览层独立出来吗？ 上面的view 可以自己去写 拓展性好一点
