### ISSUE TITLE
给大佬点歌星，watch一下，项目经常用到相机，等稳定了以后尝试下这个

### ISSUE THREAD

**Issue by nxnyk** [xionger0520/flowcamera#9]

**Comment by nxnyk** [comment]
大佬，没有java版本吗？

**Comment by xionger0520** [comment]
@nxnyk 这个就是java版本啊

**Comment by nxnyk** [comment]
> @nxnyk 这个就是java版本啊

我看readme 和源码 是 kt的呀

**Comment by xionger0520** [comment]
@nxnyk 只是DEMO用KT写的而已

**Comment by nxnyk** [comment]
> @nxnyk 这个就是java版本啊

看了下。看错了。看成demo的代码了。。大佬可以再readme里加个java版本的。。方便还没用kt的小伙伴快速使用呀~

**Comment by nxnyk** [comment]
> @nxnyk 只是DEMO用KT写的而已

话说。现在cameraX稳定了吗。。

**Comment by xionger0520** [comment]
@nxnyk 如果有技术咨询或者定制需求可以加我微信

**Comment by nxnyk** [comment]
> @nxnyk 如果有技术咨询或者定制需求可以加
